name: Generate Github pages
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements-dev.txt
        python3 -m pip install setuptools wheel
    - name: Build docs
      run: |
        (cd docs && sphinx-build -M clean . _build && sphinx-build -M html . _build)
    - name: Publish docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: "./docs/_build/html"
        cname: python-scitt.datatrails.ai
        force_orphan: true

